# REQUIREMENT : github action secret TEST_DISCORD_WEBHOOK_URL : a webhook url created from discord
name: webhook_test
permissions:
  contents: none

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  webhook_test_job:
    name: Test GitHub actions webhook TGAW1
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGO: https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Octicons-mark-github.svg/1200px-Octicons-mark-github.svg.png
    steps:
      - name: Send basic report to discord channel
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.TEST_DISCORD_WEBHOOK_URL }}
          embed-title: "TGAW1 my embed-title"
          username: "TGAW1 username"
          embed-image-url: ${{ env.GITHUB_LOGO }}
          embed-description: "TGAW1 my description"
